# Generated by Django 5.0.6 on 2024-07-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='default_organization',
            new_name='organisation',
        ),
    ]
