# Generated by Django 5.0.6 on 2024-07-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_rename_default_organization_user_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organisation',
            new_name='default_organisation',
        ),
    ]
