# Generated by Django 5.0.6 on 2024-07-08 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_rename_default_organisation_user_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='organisation',
            new_name='organisations',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='users',
            field=models.ManyToManyField(related_name='organisation', to=settings.AUTH_USER_MODEL),
        ),
    ]
